version: "2"
run:
  timeout: 5m
linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - ginkgolinter
formatters:
  enable:
    - gofmt
    - goimports
