apiVersion: v1
kind: Service
metadata:
  name: awcp-controller-metrics
  namespace: awcp-system
  labels:
    app.kubernetes.io/name: awcp-controller-manager
spec:
  selector:
    app.kubernetes.io/name: awcp-controller-manager
  ports:
    - name: https-metrics
      port: 8443
      targetPort: metrics
